apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplayer-deployment
spec:
  selector:
    matchLabels:
      app: multiplayer
  replicas: 1 
  template:
    metadata:
      labels:
        app: multiplayer
    spec:
      containers:
      - name: bitsnake-multiplayer
        pullsecret: argocd/dockerhub-secret
        image: bitsnake/multiplayer:main
        resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
        ports:
        - containerPort: 4000
      
        