apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multiplayer-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls: 
    - 
      hosts: 
        - cluster.bitsnake.win
      secretName: tls-secret-multiplayer
  rules:
    - host: cluster.bitsnake.win
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: multiplayer-service
                port:
                  number: 4000
          - path: /multiplayer
            pathType: Prefix
            backend:
              service:
                name: multiplayer-service
                port:
                  number: 4000
