apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: http://139.144.168.82/
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: multiplayer-service
            port: 
              number: 4000
