apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplayer-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: multiplayer
  template:
    metadata:
      labels:
        app: multiplayer
    spec:
      imagePullSecrets:
        - name: docker-credentials
      containers:
      - name: bitsnake-multiplayer
        image: bitsnake/multiplayer:main
        imagePullPolicy: Never
        volumeMounts:
        - name: probe-volume
          mountPath: /usr/local/multiplayer/app
        - name: modules
          mountPath: /usr/local/multiplayer/app/node_modules
        resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
        livenessProbe:
          httpGet:
            path: /health-check
            port: http-port
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 30
          periodSeconds: 5
        ports:
        - name: app-port
          containerPort: 4000
          hostPort: 4000
        - name: http-port
          containerPort: 3000
          hostPort: 3000
      volumes:
        - name: probe-volume
          hostPath:
            path: /usr/local/multiplayer/app
            type: Directory
        - name: modules
          hostPath:
            path: /usr/local/multiplayer/app/node_modules
            type: DirectoryOrCreate
            