apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplayer-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: multiplayer
  template:
    metadata:
      labels:
        app: multiplayer
    spec:
      imagePullSecrets:
        - name: docker-credentials
      containers:
      - name: bitsnake-multiplayer
        image: bitsnake/multiplayer:main
        resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
        livenessProbe:
          httpGet:
            port: app-port
          periodSeconds: 10
          timeoutSeconds: 10
        ports:
        - name: app-port
          containerPort: 4000
          hostPort: 4000
      
        